/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DesktopFailure =
  | {
      kind: "Ledger";
      message: Note;
      [k: string]: unknown;
    }
  | {
      kind: "Runtime";
      message: Note;
      [k: string]: unknown;
    }
  | {
      kind: "Native";
      message: Note;
      [k: string]: unknown;
    };
export type Note = string;
export type PageEnd = "Complete" | "More";
/**
 * An agent role scoped to its owning Cortex team.
 */
export type AgentId =
  | {
      role: GizmoAgent;
      team: "Gizmo";
    }
  | {
      role: DevelopmentAgent;
      team: "Development";
    }
  | {
      role: AiAgent;
      team: "Ai";
    }
  | {
      role: SecurityAgent;
      team: "Security";
    }
  | {
      role: SreAgent;
      team: "Sre";
    }
  | {
      role: DeliveryAgent;
      team: "Delivery";
    };
export type GizmoAgent = "GizmoPrime" | "Gizmo";
export type DevelopmentAgent =
  | "RustDev"
  | "RustRefactoring"
  | "RustVerifier"
  | "TypescriptDev"
  | "TypescriptVerifier"
  | "WebDesigner";
export type AiAgent = "TechWriter" | "TechWriterVerifier";
export type SecurityAgent = "SecurityAgent";
export type SreAgent =
  | "CicdAgent"
  | "DockerSpecialist"
  | "KubernetesSpecialist";
export type DeliveryAgent = "IntegrationAgent" | "PrAgent";
/**
 * Why held work cannot proceed, as its worker recorded it.
 */
export type Blocker =
  | {
      kind: "unblocked";
      [k: string]: unknown;
    }
  | {
      kind: "blocked";
      reason: Note;
      [k: string]: unknown;
    };
export type LeaseHealth = "current" | "expired" | "not_running";
/**
 * One observable workflow state; `Working` and `Blocked` split the active assignment phase.
 */
export type FlowState =
  | "queued"
  | "working"
  | "blocked"
  | "ready"
  | "integrated"
  | "completed"
  | "cancelled";
/**
 * The task a coordinator most recently integrated or completed.
 */
export type LatestDelivery =
  | {
      kind: "nothing";
      [k: string]: unknown;
    }
  | {
      at: number;
      kind: "delivered";
      status: FlowState;
      task: string;
      [k: string]: unknown;
    };
/**
 * Task activity bounds, not feature lifecycle events (which are not stored).
 */
export type FeatureActivity =
  | {
      kind: "empty";
      [k: string]: unknown;
    }
  | {
      first_task_at: number;
      kind: "recorded";
      last_activity_at: number;
      [k: string]: unknown;
    };
/**
 * The single headline an observer needs first; attention outranks progress.
 */
export type WorkflowCondition =
  | "empty"
  | "attention"
  | "active"
  | "waiting"
  | "finished";

export interface DesktopContract {
  failure: DesktopFailure;
  reply: DesktopReply;
  [k: string]: unknown;
}
/**
 * Every recorded feature with its totals, held work, outcomes and pull requests.
 */
export interface DesktopReply {
  features: Page;
  [k: string]: unknown;
}
/**
 * A page of bounded records. Each operation releases its connection before returning.
 */
export interface Page {
  end: PageEnd;
  records: FeatureSummary[];
  [k: string]: unknown;
}
export interface FeatureSummary {
  active: ActiveWork[];
  feature: Feature;
  latest_delivery: LatestDelivery;
  /**
   * Live tasks no other task depends on, most recently updated first.
   */
  outcomes: FeatureOutcome[];
  /**
   * Pull requests recorded in task progress extensions, most often recorded first.
   */
  pull_requests: PullRequest[];
  totals: WorkflowTotals;
  [k: string]: unknown;
}
/**
 * Work currently held by an agent, extracted without loading full task documents.
 */
export interface ActiveWork {
  agent: AgentId;
  blocker: Blocker;
  last_update: number;
  lease: LeaseHealth;
  status: FlowState;
  summary: Note;
  task: string;
  [k: string]: unknown;
}
export interface Feature {
  branch: string;
  id: string;
  objective: Note;
  version: number;
  worktree: string;
}
/**
 * A task no other recorded task depends on: something the feature delivers.
 */
export interface FeatureOutcome {
  last_update: number;
  status: FlowState;
  task: string;
  [k: string]: unknown;
}
/**
 * A pull request recorded by at least one task, with the tasks that recorded it.
 */
export interface PullRequest {
  number: number;
  /**
   * Latest update of a task that records this pull request.
   */
  recorded_at: number;
  /**
   * `owner/repository` as written in the link.
   */
  repository: string;
  /**
   * Tasks whose current progress records this pull request, most recent first.
   */
  tasks: string[];
  /**
   * Canonical `https://host/owner/repository/pull/number` link.
   */
  url: string;
  [k: string]: unknown;
}
export interface WorkflowTotals {
  activity: FeatureActivity;
  completion: Completion;
  condition: WorkflowCondition;
  counts: FlowCount[];
  /**
   * Active tasks whose lease expired before the observation.
   */
  stalled: number;
  [k: string]: unknown;
}
/**
 * Finished work over all recorded work; cancelled tasks are closed but not finished.
 */
export interface Completion {
  cancelled: number;
  finished: number;
  total: number;
  [k: string]: unknown;
}
export interface FlowCount {
  count: number;
  state: FlowState;
  [k: string]: unknown;
}
