/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DesktopFailure =
  | {
      kind: "Ledger";
      message: Note;
      [k: string]: unknown;
    }
  | {
      kind: "Runtime";
      message: Note;
      [k: string]: unknown;
    }
  | {
      kind: "Native";
      message: Note;
      [k: string]: unknown;
    };
export type Note = string;
export type DesktopContent =
  | {
      kind: "Features";
      value: Page;
      [k: string]: unknown;
    }
  | {
      kind: "Workflow";
      value: FeatureFlow;
      [k: string]: unknown;
    }
  | {
      kind: "Task";
      value: TaskV2;
      [k: string]: unknown;
    }
  | {
      kind: "History";
      value: Page3;
      [k: string]: unknown;
    };
export type PageEnd = "Complete" | "More";
export type FlowState =
  | "queued"
  | "working"
  | "blocked"
  | "ready"
  | "integrated"
  | "completed"
  | "cancelled";
/**
 * An agent role scoped to its owning Cortex team.
 */
export type AgentId =
  | {
      role: GizmoAgent;
      team: "Gizmo";
    }
  | {
      role: DevelopmentAgent;
      team: "Development";
    }
  | {
      role: AiAgent;
      team: "Ai";
    }
  | {
      role: SecurityAgent;
      team: "Security";
    }
  | {
      role: SreAgent;
      team: "Sre";
    }
  | {
      role: DeliveryAgent;
      team: "Delivery";
    };
export type GizmoAgent = "GizmoPrime" | "Gizmo";
export type DevelopmentAgent =
  | "RustDev"
  | "RustRefactoring"
  | "RustVerifier"
  | "TypescriptDev"
  | "TypescriptVerifier"
  | "WebDesigner";
export type AiAgent = "TechWriter" | "TechWriterVerifier";
export type SecurityAgent = "SecurityAgent";
export type SreAgent =
  | "CicdAgent"
  | "DockerSpecialist"
  | "KubernetesSpecialist";
export type DeliveryAgent = "IntegrationAgent" | "PrAgent";
export type RecordedActor =
  | {
      kind: "unrecorded";
      [k: string]: unknown;
    }
  | {
      agent: AgentId;
      kind: "recorded";
      [k: string]: unknown;
    };
export type EventKind =
  | "created"
  | "claimed"
  | "assigned"
  | "heartbeat"
  | "progress"
  | "checkpoint"
  | "ready"
  | "integrated"
  | "completed"
  | "requeued"
  | "cancelled";
export type Checkpoint =
  | {
      kind: "unrecorded";
    }
  | {
      commit: string;
      kind: "git";
    };
export type CheckOutcome = "passed" | "failed" | "not_run";
/**
 * V1 tasks did not record an intended owner or reporting line.
 */
export type TaskOwnership =
  | {
      kind: "Unrecorded";
    }
  | {
      assignment: TaskAssignment;
      kind: "Assigned";
    };
export type ReportingTarget =
  | {
      kind: "Host";
    }
  | {
      coordinator: GizmoAgent;
      kind: "Gizmo";
    };
export type TaskState =
  | {
      kind: "queued";
    }
  | {
      assignment: Assignment;
      kind: "active";
    }
  | {
      agent: AgentId;
      attempt: number;
      kind: "ready";
    }
  | {
      commit: string;
      kind: "integrated";
    }
  | {
      agent: AgentId;
      attempt: number;
      kind: "completed";
    }
  | {
      kind: "cancelled";
      reason: Note;
    };
export type Phase =
  | {
      kind: "working";
    }
  | {
      kind: "blocked";
      reason: Note;
    };
/**
 * Current task shape. V1 payloads are decoded by the separate legacy task record.
 */
export type TaskRecordVersion = 2;
export type Workspace =
  | {
      kind: "read_only";
    }
  | {
      kind: "feature";
    }
  | {
      branch: string;
      kind: "git";
      path: string;
    };
export type DashboardView =
  | {
      kind: "Features";
    }
  | {
      feature: string;
      kind: "Tasks";
    }
  | {
      kind: "Task";
      query: TaskQuery;
    }
  | {
      kind: "History";
      query: TaskQuery;
    };
export type DesktopRead =
  | {
      kind: "Initial";
    }
  | {
      kind: "Features";
      page: number;
    }
  | {
      feature: string;
      kind: "Workflow";
      page: number;
    }
  | {
      kind: "Task";
      query: TaskQuery;
    }
  | {
      kind: "History";
      page: number;
      query: TaskQuery;
    };

export interface DesktopContract {
  failure: DesktopFailure;
  reply: DesktopReply;
  request: DesktopRead;
  [k: string]: unknown;
}
export interface DesktopReply {
  content: DesktopContent;
  selection: DesktopSelection;
  [k: string]: unknown;
}
/**
 * A page of at most 100 records. Each operation releases its connection before returning.
 */
export interface Page {
  end: PageEnd;
  records: Feature[];
  [k: string]: unknown;
}
export interface Feature {
  branch: string;
  id: string;
  objective: Note;
  version: number;
  worktree: string;
}
export interface FeatureFlow {
  counts: FlowCount[];
  feature: Feature;
  observed_at: number;
  tasks: Page2;
  [k: string]: unknown;
}
export interface FlowCount {
  count: number;
  state: FlowState;
  [k: string]: unknown;
}
/**
 * A page of at most 100 records. Each operation releases its connection before returning.
 */
export interface Page2 {
  end: PageEnd;
  records: TaskFlow[];
  [k: string]: unknown;
}
export interface TaskFlow {
  checkpoints: RecordedCommit[];
  created_by: RecordedActor;
  history_end: PageEnd;
  integrations: RecordedCommit[];
  milestones: Milestone[];
  task: TaskV2;
  worker: RecordedActor;
  [k: string]: unknown;
}
export interface RecordedCommit {
  actor: AgentId;
  at: number;
  commit: string;
  revision: number;
  [k: string]: unknown;
}
export interface Milestone {
  actor: AgentId;
  at: number;
  attempt: number;
  kind: EventKind;
  note: Note;
  revision: number;
  [k: string]: unknown;
}
export interface TaskV2 {
  common: TaskCommon;
  ownership: TaskOwnership;
  state: TaskState;
  version: TaskRecordVersion;
  workspace: Workspace;
}
/**
 * Shared task fields in V2 and later records.
 * Keep this shape stable for retained readers; changed field meanings need a new type.
 */
export interface TaskCommon {
  acceptance: Note[];
  attempt: number;
  checkpoint: Checkpoint;
  created_at: number;
  dependencies: string[];
  feature: string;
  id: string;
  last_progress: number;
  last_update: number;
  objective: Note;
  progress: Progress;
  revision: number;
}
export interface Progress {
  checks: Check[];
  /**
   * Task-specific data only. Coordination never interprets these keys.
   */
  extensions?: {
    [k: string]: unknown;
  };
  findings: Note[];
  next_steps: Note[];
  summary: Note;
}
export interface Check {
  command: Note;
  evidence: Note;
  outcome: CheckOutcome;
}
/**
 * The intended owner and reporting line survive every task state and attempt.
 */
export interface TaskAssignment {
  agent: AgentId;
  reports_to: ReportingTarget;
}
export interface Assignment {
  agent: AgentId;
  attempt: number;
  expires_at: number;
  phase: Phase;
}
/**
 * A page of at most 100 records. Each operation releases its connection before returning.
 */
export interface Page3 {
  end: PageEnd;
  records: Event[];
  [k: string]: unknown;
}
export interface Event {
  actor: AgentId;
  kind: EventKind;
  note: Note;
  task: TaskV2;
  version: number;
}
export interface DesktopSelection {
  page: number;
  view: DashboardView;
  [k: string]: unknown;
}
export interface TaskQuery {
  feature: string;
  task: string;
}
